
name: pytest

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: update
      run: sudo apt update -y
    - name: Install dependencies
      run: sudo apt install -y python3-pytest python3-pip
    - run: ln -s src mailsort
    - name: Test with pytest
      run: pytest-3 test.py
